---
# Based on various parts of:
# https://docs.docker.com/install/linux/docker-ce/ubuntu/
# https://github.com/ansible/awx/blob/devel/INSTALL.md
# https://docs.gitlab.com/omnibus/docker/
#
# Config of AWX based on these notes: (Don't use it as an install guide!!)
# https://www.howtoforge.com/how-to-install-ansible-awx-with-nginx-reverse-proxy-on-ubuntu-1804/

- name: Install prerequisites
  gather_facts: false
  hosts: all
  become: true
  tasks:
  - include_tasks: Playbooks/A00.Prerequsites.yml
  - include_tasks: Playbooks/B00.Install.Gitlab.yml
  - include_tasks: Playbooks/C00.Install.AWX.yml
